use crate::cli;

pub(crate) fn proxy_args_from_node_forward(args: cli::NodeForwardArgs) -> cli::ProxyArgs {
    cli::ProxyArgs {
        target: args.target,
        listen: args.listen,
        tcp_target: args.tcp_target,
        ssh_args: args.ssh_args,
        ssh_command: None,
        user: args.user,
        port: args.port,
        identity: args.identity,
        config: args.config,
        known_hosts: args.known_hosts,
        accept_new: args.accept_new,
        insecure_ignore_host_key: args.insecure_ignore_host_key,
        jump: args.jump,
        remote_path: args.remote_path,
        remote_bin: args.remote_bin,
        deploy: args.deploy,
        remote_os: args.remote_os,
        remote_transport: args.remote_transport,
        remote_tcp: args.remote_tcp,
        remote_control: args.remote_control,
        remote_quic: args.remote_quic,
        allow_plain_tcp: args.allow_plain_tcp,
        remote_tls: args.remote_tls,
        remote_ca: args.remote_ca,
        remote_name: args.remote_name,
        remote_client_cert: args.remote_client_cert,
        remote_client_key: args.remote_client_key,
        remote_token: args.remote_token,
        egress_proxy: args.egress_proxy,
        reconnect_delay_secs: args.reconnect_delay_secs,
        reconnect_max_delay_secs: args.reconnect_max_delay_secs,
        connect_timeout_secs: args.connect_timeout_secs,
        transport_pool_size: args.transport_pool_size,
        pool_policy: args.pool_policy,
        workload_hint: args.workload_hint,
        quic_max_bidi_streams: args.quic_max_bidi_streams,
        quic_stream_receive_window: args.quic_stream_receive_window,
        quic_receive_window: args.quic_receive_window,
        quic_keep_alive_interval_secs: args.quic_keep_alive_interval_secs,
        quic_idle_timeout_secs: args.quic_idle_timeout_secs,
        ssh_session_pool_size: args.ssh_session_pool_size,
        ssh_session_pool_source: args.ssh_session_pool_source,
        ssh_session_pool_reason: args.ssh_session_pool_reason,
        ssh_session_pool_warning: args.ssh_session_pool_warning,
        transport_pool_source: args.transport_pool_source,
        transport_pool_reason: args.transport_pool_reason,
        transport_selection_source: args.transport_selection_source,
        transport_selection_reason: args.transport_selection_reason,
        preflight_recommended_fallback: args.preflight_recommended_fallback,
        preflight_selected_reason: args.preflight_selected_reason,
        preflight_repair_hint: args.preflight_repair_hint,
        preflight_candidate_failures: args.preflight_candidate_failures,
        no_reconnect: args.no_reconnect,
        control_listen: None,
    }
}

pub(crate) fn reverse_args_from_node_reverse(args: cli::NodeReverseArgs) -> cli::ReverseTaskArgs {
    cli::ReverseTaskArgs {
        target: args.target,
        remote_listen: args.remote_listen,
        tcp_target: args.tcp_target,
        ssh_args: args.ssh_args,
        user: args.user,
        port: args.port,
        identity: args.identity,
        config: args.config,
        known_hosts: args.known_hosts,
        accept_new: args.accept_new,
        insecure_ignore_host_key: args.insecure_ignore_host_key,
        jump: args.jump,
        remote_path: args.remote_path,
        remote_bin: args.remote_bin,
        deploy: args.deploy,
        remote_os: args.remote_os,
        egress_proxy: args.egress_proxy,
        reconnect_delay_secs: args.reconnect_delay_secs,
        reconnect_max_delay_secs: args.reconnect_max_delay_secs,
        connect_timeout_secs: args.connect_timeout_secs,
        transport_pool_source: args.transport_pool_source,
        transport_pool_reason: args.transport_pool_reason,
        no_reconnect: args.no_reconnect,
    }
}
